# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vt6gNBOIqC2ak9xHkPmEvWgY-e3bfUfc
"""

#class

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

#inheritance

class vehicle:
  def general_usage (self):
    print("general usage:transporation")

class car (vehicle):   #derive class and vehicle is base class
  def __init__(self):  # Indent this block under the 'car' class
     print("i am car")
     self.wheels=4
     self.has_roof = True  # Change 'true' to 'True'

  def specific_usage(self):  # Indent this block under the 'car' class
      print("specific use: commute to work,vacation with family")

class Motorcycle (vehicle):
  def __init__(self):  # Indent this block under the 'car' class
     print("i am motorcyle")
     self.wheels=4
     self.has_roof = True

  def specific_usage(self):  # Indent this block under the 'car' class
      print("specific use: roadtrip , racing")

c = Motorcycle() #identify of class motorcycle
c.general_usage()
c.specific_usage()

c = car()
c.general_usage()
c.specific_usage()