# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXRPrT9UTOTN-aRd4thmVaxWP4O2Uk-f
"""

#Dictionary allows you to store key value pairs
#also known as maps , hashtables, associate arrays

d={"tom":6447373467373 ,"rob":643737373773}
print(d)

#Access any element from dict based on key
d={"saj":7478388384,"mili":74757477,"jam":473737377}
x=d["saj"]
print(x)

#Add new entry or item
d={"saj":7478388384,"mili":74757477,"jam":473737377}

d["sam"] = "2636372"
print(d)

#remove element from dict

d={"saj":7478388384,"mili":74757477,"jam":473737377}
del d["saj"]
print(d)

#how do you print all the directory value
d={"saj":7478388384,"mili":74757477,"jam":473737377}
for x in d.values():
  print(x)

#check specific person name in dict
d={"saj":7478388384,"mili":74757477,"jam":473737377}
"saj"in d

d={"saj":7478388384,"mili":74757477,"jam":473737377}
"sameer"in d

#Tuples is a list of values grouped together
#tuples are immutable
#list all values have similar meaning(homogenous)
#tuples all values have different meaning (heterogeneous)

d=("saj","jam","mili")
print(d)

#Acces tuples basis of index number
d=("saj","jam","mili")
print(d[1])