# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0qJDewNMFMOZPJVdt1lOGHNuctpI1UB
"""

#for loop used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string

#Store montly expenses in a list and find out total expenses for all months

exp = [2340, 2500, 2100, 3100, 2900] #list

# total = exp[0] + exp[1] + exp[2] + exp[3] + exp[4]

total=0
for item in exp:      #for each of item in exp list do this
  total= total+item

print(total)

#Print 1 to 10 using range()
for i in range (1,11):      # put index from start to stop -1 to 10+1
  print(i) # i is variable in value

#In our monthly expenses example print month number and expenses and then in the end print total expenses

exp = [2340, 2500, 2100, 3100, 2900]
total=0
for i in range(len(exp)): # length function
  print('Month: ' + str(i+1) + ' Expenses: ' + str(exp[i]))  # Use + to concatenate strings
  total = total + exp[i]

print('Total expenses:', total) # Print the total expenses

#search  for lost car key  in home and when found stop searching

key_location="chair"
locations=["garage","living room","chair","kitchen"]
for i in locations:
 if i==key_location: #comparison operator
   print("key found in ", i)
   break #it will just come out of for loop it will terminate
else:
  print("key is not found in",i)