# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoaZIQtCvIwfC1yqmMEnA4tsKhD46lXv
"""

#function is block of code that performs specific task
#functions makes code more modular

#You have two list of numbers and you need to find total of each of these list
tom_exp_list = [100,200,300]
bob_exp_list = [200,300,500] #list

total=0

#for loop for tom list
for item in tom_exp_list:
  total=total+item

print(total)

#for loop for bob list
for item in bob_exp_list:
  total=total+item

print(total)

def calculate_total(exp):
  total=0
  for item in exp:
    total=total+item
    return total

tom_exp_list=[]

hfnewndjfi

