# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5eMSzbF1L1BEJZYwqU9A-z9ESdjgvPs
"""

#Generators
def remote_control_next():  #define
    yield "cnn"
    yield "espn"

itr= remote_control_next()
itr

next(itr)

next(itr)

#fibonaacci sequence using generator
def fib():
  a,b =0,1
  while True:
    yield a
    a,b = b, a+b
for f in fib():
  if f>50:
    break  # Indent the break statement to be part of the if block
  print(f)  # Indent the print statement to be outside the if block

