# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhaLFLJAMMtVokSyywEYATzpglKAikyq
"""

#used to decide whether a certain statement or block of statements will be executed or not.

#Write a program that asks user to enter a number.Program should tell if number is odd even

num= input("Enter a number: ")
num = int(num)
if num%2==0: #to find remainder used percentage symbol
  print("number is even")
else:
  print("number is odd")

#Write a program that asks user to enter dish name and it should print which cuisine is that dish

indian=["samosa","daal","naan"] #make list
chinese=["egg role","noodles","fried rice"]
italian=["pasta","pizza","risotto"]

dish=input("Enter a dish name:") #ask user

if dish in indian: #if dish that user enter belong to this dish
  print("indian")
elif dish in chinese:
  print("chinese")
elif dish in italian:
  print("italian")
else:
  print("based on little knowledge i have i dont know which cuisine is", dish)