# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlWe32A6k7tcBguZrZOGZjMeIgkLyavC
"""

#iterators
a =["hey","bro"] # create string
for i in a:  #for loop
  print(i)

dir(a) #built in mathods

itr=iter(a) #iter methods
print(itr)

#using iterator object we can to next element in list
next(itr)

next(itr)

#reverse iterators
itr= reversed(a)
next(itr)

next (itr)



