# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Wv4fOP9tsUgoG7kSPUz88zCQHTwC2l5
"""

#List sets Comprehensions
#list comprehension provides a way to transform one list into another

numbers = [1,2,3,4,4,5,6]
even = []
for i in numbers:
  if i%2==0:
    even.append(i)

#one line by list comprehenesion
even =[i for i in numbers if i%2==0]  #for loop and condn
even

#square of all numbers
sqr_numbers = [i**i for i in numbers]
sqr_numbers

#set comprehension
#set unorder collection of unique order
s=set([1,2,3,4,5,6])
s

#generate another set which have only even numbers
even= {i for i in s if i%2==0}
even

#dictionary comprehension
cities =["mumbai", "nyc","paris"] #key is name of city
countries=["india","usa","france"] #value is name of countries
z=zip(cities,countries) #build in function in python
z

for a in z:
  print(a)

d={city:country for city , country in zip(cities,countries ) }
d

