# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfeynaZWJD5ewLVbtPkeQsaVn54lF4SH
"""

#Modules is a way to reuse a code written by someone else

# math module
import math
math.sqrt(16)

math.pow(2,5)

dir(math) #all function available in math func

math.pi

math.log10(100)

math.log10(1000)

math.floor(2.3)

import calendar

cal=calendar.month(2018,1)
print(cal)

calendar.isleap(2020)

dir(calendar)

