# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DL0GTG97empJvLdepL_V5fTrZ2KokOv2
"""

#multithreading is a way of achieving multitasking.
#In multithreading, the concept of threads is used

#for a given list numbers print square and cube of every numbers
import time
import threading  #module for multi threading

def calc_square(numbers):
  print("calculate square numbers")
  for n in numbers:
    time.sleep(0.2)
    print('square:',n*n)

def calc_cube(numbers):
  print("calculate cube of numbers")
  for n in numbers:
    time.sleep(0.2)
    print('cube:',n*n*n)

arr =[2,3,8,9]

t = time.time()

t1 = threading.Thread(target=calc_square, args=(arr,))
t2 = threading.Thread(target=calc_cube, args=(arr,))

t1.start()
t2.start()

t1.join()
t2.join()


print("done in:", time.time()-t)
print("hah... i am done with all my work now!")



